// AUTO-GENERATED by scripts/build-mood-images.mjs — do not edit by hand.
// Curated images shown when a mood tile is clicked, keyed by mood id.
export const MOOD_IMAGES: Record<string, string[]> = {
  "sun-soaked": [
    "/assets/mood/sun-soaked/japandi__samara.jpg",
    "/assets/mood/sun-soaked/japandi__tulum.jpg",
    "/assets/mood/sun-soaked/japandi__tulum__2.jpg",
    "/assets/mood/sun-soaked/minimalist__bali.jpg",
    "/assets/mood/sun-soaked/minimalist__bali__2.jpg",
    "/assets/mood/sun-soaked/minimalist__barcelona.jpg",
    "/assets/mood/sun-soaked/minimalist__barcelona__2.jpg",
    "/assets/mood/sun-soaked/minimalist__tulum.jpg",
    "/assets/mood/sun-soaked/minimalist__tulum__2.jpg",
    "/assets/mood/sun-soaked/minimalist__tulum__3.jpg",
    "/assets/mood/sun-soaked/modern__tulum.jpg",
    "/assets/mood/sun-soaked/scandinavian__bali.jpg",
    "/assets/mood/sun-soaked/scandinavian__bali__2.jpg",
    "/assets/mood/sun-soaked/scandinavian__bali__3.jpg",
    "/assets/mood/sun-soaked/scandinavian__barcelona__2.jpg",
    "/assets/mood/sun-soaked/traditional__barcelona.jpg",
    "/assets/mood/sun-soaked/traditional__barcelona__2.jpg",
    "/assets/mood/sun-soaked/traditional__barcelona__3.jpg",
    "/assets/mood/sun-soaked/traditional__samara.jpg",
    "/assets/mood/sun-soaked/traditional__samara__3.jpg"
  ],
  "buzzing": [
    "/assets/mood/buzzing/industrial__berlin.jpg",
    "/assets/mood/buzzing/minimalist__barcelona.jpg",
    "/assets/mood/buzzing/minimalist__paris.jpg",
    "/assets/mood/buzzing/minimalist__tokyo.jpg",
    "/assets/mood/buzzing/modern__barcelona.jpg",
    "/assets/mood/buzzing/modern__mexico-city.jpg",
    "/assets/mood/buzzing/modern__new-york.jpg",
    "/assets/mood/buzzing/modern__new-york__2.jpg",
    "/assets/mood/buzzing/modern__paris.jpg",
    "/assets/mood/buzzing/scandinavian__berlin.jpg"
  ],
  "nature": [
    "/assets/mood/wild/japandi__bali.jpg",
    "/assets/mood/wild/japandi__bali__2.jpg",
    "/assets/mood/wild/japandi__kiruna.jpg",
    "/assets/mood/wild/japandi__leticia.jpg",
    "/assets/mood/wild/japandi__leticia__2.jpg",
    "/assets/mood/wild/japandi__leticia__3.jpg",
    "/assets/mood/wild/japandi__reykjavik.jpg",
    "/assets/mood/wild/minimalist__rovaniemi.jpg",
    "/assets/mood/wild/minimalist__tokyo.jpg",
    "/assets/mood/wild/modern__reykjavik.jpg",
    "/assets/mood/wild/modern__tokyo.jpg",
    "/assets/mood/wild/scandinavian__bali__2.jpg",
    "/assets/mood/wild/scandinavian__rovaniemi.jpg",
    "/assets/mood/wild/traditional__leticia__3.jpg",
    "/assets/mood/wild/traditional__reykjavik.jpg",
    "/assets/mood/wild/traditional__reykjavik__2.jpg",
    "/assets/mood/wild/traditional__rovaniemi.jpg"
  ],
  "storied": [
    "/assets/mood/storied/industrial__barcelona.jpg",
    "/assets/mood/storied/industrial__barcelona__2.jpg",
    "/assets/mood/storied/japandi__berlin.jpg",
    "/assets/mood/storied/minimalist__berlin.jpg",
    "/assets/mood/storied/minimalist__berlin__2.jpg",
    "/assets/mood/storied/modern__tulum.jpg",
    "/assets/mood/storied/traditional__barcelona.jpg",
    "/assets/mood/storied/traditional__mexico-city.jpg",
    "/assets/mood/storied/traditional__mexico-city__2.jpg"
  ],
  "wintry": [
    "/assets/mood/wintry/japandi__reykjavik.jpg",
    "/assets/mood/wintry/minimalist__kiruna.jpg",
    "/assets/mood/wintry/scandinavian__kiruna.jpg",
    "/assets/mood/wintry/scandinavian__rovaniemi.jpg",
    "/assets/mood/wintry/scandinavian__rovaniemi__2.jpg",
    "/assets/mood/wintry/traditional__reykjavik.jpg",
    "/assets/mood/wintry/traditional__rovaniemi.jpg",
    "/assets/mood/wintry/traditional__rovaniemi__2.jpg",
    "/assets/mood/wintry/traditional__rovaniemi__3.jpg"
  ]
}
